---
- src: https://github.com/Emergent360/launch_aws_vpc.git
- src: https://github.com/Emergent360/create_vpc_peering.git
- src: https://github.com/Emergent360/add_domain_user.git
- src: https://github.com/Emergent360/add_domain_computer.git
- src: https://github.com/Emergent360/launch_windows_ami.git
- src: https://github.com/Emergent360/update_domain_user.git